### ISSUE TITLE
Token Bucket - test cases?

### ISSUE THREAD

**Issue by nmondal** [AshishK-10/Blox_questions#1]
How do you test it? How do you know it works?
Suppose I have 1000 different connections from 1000 different IPs now what happens?
https://github.com/AshishK-10/Blox_questions/blob/main/ans3/ans3.js

**Comment by AshishK-10** [comment]
Sir, being a fresher I haven't practically worked on rate-limiting applications, but theoretically if I have 1000 different connections from 1000 different IPs, each connection would be treated independently regarding rate limiting. Each IP address would be considered as a separate client, and rate limiting would be applied individually for each IP address or connection.  Here I can save the hash which contains the IPs and tokens left for it, which will be saved in database and will be
updated according to the use.

Let's assume We have a rate limit of 15 calls per minute for each client (IP address): 

Here's what would happen for each connection from different IPs:

Connection 1: If Connection 1 makes 15 API calls within a minute, it will be rate-limited for that minute. Any additional API calls from this client will be rejected until the next minute.

Connection 2: If Connection 2 makes 10 API calls within a minute, it still has 5 tokens left in its token bucket. It can make 5 more API calls before hitting the rate limit.

This process continues for each unique IP address, and each connection is rate-limited independently of the others. The token bucket algorithm ensures that the rate limit is enforced fairly for each client, regardless of the total number of connections.

**Comment by nmondal** [comment]
Did you test it?
Did you run it ?
What are the test cases?
Can you please write down test cases?

**Comment by AshishK-10** [comment]
Yes, Sir to check the proper functioning of the algorithm, I ran a loop for 16 and 20 times, to check for the penality waiting and execution of the api, it worked according to the constraints.

**Comment by nmondal** [comment]
So this algorithm would be run in actual , sequentially in a single thread of execution?

**Comment by AshishK-10** [comment]
Yes sir, It will work.
