### ISSUE TITLE
The parser does not work, it was not tested - at all

### ISSUE THREAD

**Issue by nmondal** [AshishK-10/Blox_questions#3]
Basic stuff fails:

```js
const jsonString = 'too';
const parsedData = customJsonParser(jsonString);
console.log(parsedData)
```
produce `false` while
```js
const jsonString = 'bar';
```
produce undefined.
Moreover :

```js
const jsonString = '{ "x" }';
```
produces:

```
{ '': ' }' }
```

**Comment by AshishK-10** [comment]
Sir, I have made some changes in the parser function, it now checks for the proper json file, but still being a custom parcer, it may fail on some edge cases or complex string, improved code is pushed again.

**Comment by nmondal** [comment]
How did you test it? What subjects in CS did you apply to test it?
How do you formally test a JSON parser?

**Comment by AshishK-10** [comment]
I, by mistake skipped the check function to check for boolean values, thatswhy it produces an error, as it checks whether the value is in  ""  or not, or is it a number. I will fix this minor issue.
